name: Lint

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    lint:
        name: lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-go@v5
              with:
                  go-version-file: "go.mod"
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                  args: --timeout 120s --max-same-issues 50 -c ./configs/.golangci.yaml
